// @platform/server — the server-authoritative pipeline engine (StateStore, dispatch,
// transition, WorkerPool, RunObserver, gate-keyed resolve, board/thread HTTP+SSE).
// Public surface consumed by the app's composition root.
export { db, databaseUrl, closeDb } from './db/client.js'
export { atizarEnv } from './env.js'
export type { Db } from './db/client.js'
export { runMigrations } from './db/migrate.js'
export { resetDb, resetCredentials, resetAll } from './db/reset.js'
export { startupSweep } from './sweep.js'
export { makePipelineService } from './pipelineService.js'
export type { PipelineService, DispatchRequest, TraceSnapshot } from './pipelineService.js'
export { createPipelineRoutes } from './routes.js'
export type { AgentRuntime } from './runObserver.js'
export { makeActivityLog } from './activity.js'
export type { ActivityEntry, ActivityLog } from './activity.js'
export { resolveCredential, registerResolver } from './resolveCredential.js'
export type { ResolveCtx, ResolveDeps } from './resolveCredential.js'
export { makeCredentialStore } from './credentialStore.js'
export type { CredentialStore, StoredCredential } from './credentialStore.js'
export { oauthProvider } from './oauthProviders.js'
export type { OAuthProvider } from './oauthProviders.js'
export { createConnectRoutes } from './connectRoutes.js'
export type { ConnectRoutesDeps, ConnectionDescriptor } from './connectRoutes.js'
